//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phase3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.ModelBinding;

    public partial class Film
    {
        public int Film_ID { get; set; }

        [Required(ErrorMessage = "Title cannot be left empty!")]
        [RegularExpression("[A-Z0-9][A-Z a-z0-9.?/: !&-]*", ErrorMessage = "Invalid Title!")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description cannot be left empty!")]
        [RegularExpression("[A-Z 0-9][A-Z a-z0-9.?&/: -]*", ErrorMessage = "Invalid Description!")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Release Year cannot be left empty!")]
        [Range(1900, 2021, ErrorMessage = "Invalid Release Year!")]
        public int Release_Year { get; set; }

        [Range(7, 999, ErrorMessage = "Invalid Release Year!")]
        public Nullable<int> Rental_Duration { get; set; }

        [Range(50, 1000, ErrorMessage = "Invalid Rental Rate!")]
        public Nullable<decimal> Rental_Rate { get; set; }

        [Range(5, 300, ErrorMessage = "Invalid Runtime!")]
        public Nullable<int> Length { get; set; }

        [Range(50, 1000, ErrorMessage = "Invalid Replacement Cost!")]
        public Nullable<decimal> Replacement_Cost { get; set; }

        [Range(0.1, 10, ErrorMessage = "Invalid Rating!")]
        public Nullable<decimal> Rating { get; set; }

        [Required(ErrorMessage = "Cast cannot be left empty!")]
        [RegularExpression("[A-Z][A-Z a-z., -]*", ErrorMessage = "Invalid Cast!")]
        public string Actors { get; set; }

        [Required(ErrorMessage = "Genre cannot be left empty!")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Language cannot be left empty!")]
        public string Language { get; set; }
    }
}
